#!/bin/bash
APP_NAME="tapioca"
BINARY="/home/tapioca/mongodb-linux-x86_64-rhel70-4.4.0/bin/mongo"
USER="mongosys"
PASS="Irontoe1234"
CONF_HOSTS=""
S1_HOSTS="192.168.1.11:27001"
S2_HOSTS=""
S3_HOSTS=""
S4_HOSTS=""
DB="admin" 


echo "Shard 1 Information"
echo "------------------------------"
$BINARY mongodb://$USER:$PASS@$S1_HOSTS/$DB --eval "db.printReplicationInfo(); printjson(db.adminCommand('listDatabases')); db.printSlaveReplicationInfo(); rs.status()"
